# Generated by Django 4.1.5 on 2023-01-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_transaction_details_reciever_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='id',
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='transaction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
