# Generated by Django 4.1.5 on 2023-01-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_transaction_details_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='transaction_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
