# Generated by Django 4.1.5 on 2023-01-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_transaction_details_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='transaction_details',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
