# Generated by Django 4.1.5 on 2023-01-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_transaction_details_transaction_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='amount',
            field=models.FloatField(default=0),
        ),
    ]
