# Generated by Django 4.1.5 on 2023-01-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_transaction_details_status_for_reciever_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='transaction_time',
            field=models.DateField(auto_now_add=True),
        ),
    ]
