# Generated by Django 4.1.5 on 2023-01-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_transaction_details_transaction_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction_details',
            name='transaction_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
