# Generated by Django 4.1.5 on 2023-01-22 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_alter_transaction_details_transaction_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction_details',
            old_name='transaction_time',
            new_name='date',
        ),
    ]
