# Generated by Django 4.1.5 on 2023-01-22 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_transaction_details_isdebit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction_details',
            name='isDebit',
        ),
    ]
