# Generated by Django 4.1.5 on 2023-01-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_transaction_details_isdebit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction_details',
            name='memo',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
